# Generated by Django 4.1.3 on 2024-02-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=100)),
                ('roast_level', models.CharField(max_length=50)),
                ('acidity', models.CharField(max_length=50)),
                ('com', models.CharField(max_length=100)),
                ('three_letters', models.CharField(max_length=3)),
            ],
        ),
    ]
