# Generated by Django 4.1.3 on 2024-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='acidity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='co_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='com',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast_level',
            field=models.CharField(max_length=255),
        ),
    ]
